import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import occtImport from "occt-import-js";

const [, , inputPath, outputPath] = process.argv;

if (!inputPath || !outputPath) {
  console.error("Usage: node tools/motor-story/step-to-obj.mjs <input.step|input.brep> <output.obj>");
  process.exit(1);
}

const input = await fs.readFile(inputPath);
const occt = await occtImport();
const extension = path.extname(inputPath).toLowerCase();
const triangulation = {
  linearUnit: "millimeter",
  linearDeflectionType: "bounding_box_ratio",
  linearDeflection: 0.001,
  angularDeflection: 0.2
};
const result = extension === ".brep" || extension === ".brp"
  ? occt.ReadBrepFile(input, triangulation)
  : occt.ReadStepFile(input, triangulation);

if (!result.success || !result.meshes.length) {
  throw new Error(`Unable to triangulate ${inputPath}`);
}

let vertexOffset = 1;
let normalOffset = 1;
const lines = [
  "# Generated by occt-import-js for the motor scroll-story render pipeline.",
  "# Millimeter coordinates; Blender imports and scales them to meters."
];

for (const [meshIndex, mesh] of result.meshes.entries()) {
  const name = safeName(mesh.name || `part-${meshIndex + 1}`);
  const positions = mesh.attributes.position.array;
  const normals = mesh.attributes.normal?.array ?? [];
  const indices = mesh.index.array;
  lines.push(`o ${name}`);

  for (let index = 0; index < positions.length; index += 3) {
    lines.push(`v ${positions[index]} ${positions[index + 1]} ${positions[index + 2]}`);
  }

  for (let index = 0; index < normals.length; index += 3) {
    lines.push(`vn ${normals[index]} ${normals[index + 1]} ${normals[index + 2]}`);
  }

  for (let index = 0; index < indices.length; index += 3) {
    const face = [indices[index], indices[index + 1], indices[index + 2]].map((value) => {
      const vertex = vertexOffset + value;
      const normal = normalOffset + value;
      return normals.length ? `${vertex}//${normal}` : String(vertex);
    });
    lines.push(`f ${face.join(" ")}`);
  }

  vertexOffset += positions.length / 3;
  normalOffset += normals.length / 3;
}

await fs.mkdir(path.dirname(path.resolve(outputPath)), { recursive: true });
await fs.writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote ${result.meshes.length} meshes to ${outputPath}`);

function safeName(value) {
  return value.trim().replace(/[^a-zA-Z0-9._-]+/g, "-") || "part";
}

